<a href="https://colab.research.google.com/github/HiddenEasyy/francisco/blob/master/P6_FONSECA_nunpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Taller** 6

Primero importamos las librerias para leer el csv y las otras para graficar

In [32]:
#import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Le damos la ruta del archivo csv para que pueda leer con el comadno de NumPy

In [73]:
#Cargar el archivo en listta python
with open("iris.csv", "r") as file:
    lines = file.readlines()
    data_list = [line.strip().split(",") for line in lines[1:]]
#Pasar el archivo a un arreglo de numpy
iris = np.array(data_list)

In [77]:


# Cargar el archivo CSV en un array de NumPy
iris = np.genfromtxt('/content/iris.csv', delimiter=',', skip_header=True, dtype=float)
#Eliminar una columna que no contiene numeros flotantes
iris_sin_variety = iris[:, :-1]


In [94]:
#iris.shape #nos da el numero de datos en renglones y columnas
iris.shape

(150, 5)

In [97]:
# Acceder a una columna específica: sepal.length
sepal_length = iris[:, 0]

#print(sepal_width_y_petal_length)
print(sepal_length)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [ ]:
# Acceder a múltiples columnas: sepal.width y petal.length
sepal_width_y_petal_length = iris[:, [1, 2]]
print(sepal_width_y_petal_length)

In [105]:
# Calcular la media de una columna (por ejemplo, sepal.width)
mean_sepal_width = np.mean(iris[:, 1])
mean_sepal_length = np.mean(iris[:, 0])

#Promedio del area del sepalo
prom_sepal= mean_sepal_length*mean_sepal_width
print("La media de la columna sepal.width es: ",mean_sepal_width)
print("La media de la columna sepal.length es: ",mean_sepal_length)
print("El promedio del area del sepalo es: ", prom_sepal)

La media de la columna sepal.width es:  3.0573333333333337
La media de la columna sepal.length es:  5.843333333333334
El promedio del area del sepalo es:  17.86501777777778


In [100]:
# Calcular la media de una columna petalo L y A
mean_petal_width = np.mean(iris[:, 2])
mean_petal_length = np.mean(iris[:, 3])

print("La media de la columna petal.width es: ",mean_petal_width)
print("La media de la columna petall.length es: ",mean_petal_length)

La media de la columna petal.width es:  3.7580000000000005
La media de la columna petall.length es:  1.1993333333333336


In [104]:
#Calcular el promedio de los petalos
prom_petal=mean_petal_length * mean_petal_width
print(prom_petal)

4.507094666666668


In [102]:
# Filtrar filas donde sepal.length es mayor que 7.0
#Elimine la columna variety ya que no la detecta porque estoy usando solo flotantes
sepal_length_mayor = iris_sin_variety[iris[:, 0] > 7.0]

print(sepal_length_mayor)

[[7.1 3.  5.9 2.1]
 [7.6 3.  6.6 2.1]
 [7.3 2.9 6.3 1.8]
 [7.2 3.6 6.1 2.5]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [7.7 2.8 6.7 2. ]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [7.7 3.  6.1 2.3]]
